# Generated by Django 2.2.7 on 2019-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
